// Blog Posts Data
// This file is automatically generated by build.py
// Do not edit manually - run 'python3 build.py' to regenerate

const blogPosts = [
    {
        "title": "Needtoknowism",
        "url": "/posts/a-warning/",
        "date": "2025-09-24",
        "dateDisplay": "September 24 2025",
        "excerpt": "Be wary of assuming you have created focus by restricting vision."
    },
    {
        "title": "Blind",
        "url": "/posts/blind/",
        "date": "2025-09-03",
        "dateDisplay": "September 03 2025",
        "excerpt": "A huge scrape against the right hand curb. The final straw in a litany of stupid mistakes.“Fuuuuu-!” I cry. Later I will cry."
    },
    {
        "title": "Am-Dram Returns",
        "url": "/posts/am-dram-returns/",
        "date": "2025-08-14",
        "dateDisplay": "August 14 2025",
        "excerpt": "There's maybe fifty of us in there. It feels like five hundred. Whatever play was on would always devolve into pantomime on that stage. I can see my Dad up there, some silly character. Some of my mates Dad's too who I vaguely knew worked in London most the week and most weekends were now, impossibly, here. I remember one of them - maybe a pirate, maybe an ugly sister - whatever he was, he was in a wig. Shouldn't it have been us up there? After all - we were the ten year olds? West Horsley village hall was small. Really small. It certainly made it easy to own the stage. Regardless, we were all having uproarious fun."
    },
    {
        "title": "Opossum Omnipotent",
        "url": "/posts/opossum-omnipotent/",
        "date": "2025-04-01",
        "dateDisplay": "April 01 2025",
        "excerpt": "Archibald sneered Archibald snared He must defend himself Look scary, look DEAD No one wants to be near death What was that A bright light A fire No… a lamb Covered in blood, it’s own The lamb spoke A sword What is that feeling Archibald never knew peace He was desperate for it He asked the lamb to stay The lamb did Archibald didn’t see him anymore But knew he was there He could sense him Inside, all around The lamb was strong and he shared His strength Archibald stopped playing dead Though it was part of his nature It wasn’t his nature anymore Because of the lamb Because of the blood Because he was loved The lamb became a fortress For an opossum made new And Archibald had peace No more death Not ever Only everlasting joy And life With the lamb"
    },
    {
        "title": "Heritage",
        "url": "/posts/heritage/",
        "date": "2025-02-22",
        "dateDisplay": "February 22 2025",
        "excerpt": "My father was a man I never knew I arrived as he was that day and we became ourselves together"
    },
    {
        "title": "The Spring Hare",
        "url": "/posts/the-spring-hare/",
        "date": "2025-02-10",
        "dateDisplay": "February 10 2025",
        "excerpt": "Gather around the great lantern young man, Light up the old dark fields and search for them those bright glistening eyes the spring hare"
    },
    {
        "title": "The Wolf",
        "url": "/posts/the-wolf/",
        "date": "2025-02-01",
        "dateDisplay": "February 01 2025",
        "excerpt": "He used to run around the moors after dark. Picking up pace across poorly tended trails in just the light of his head-torch. He thought of nothing those nights. Seeing, no one. Hearing, no one. Whenever the fog fell, he would see the wolf. He would turn his lamp to its lowest setting to reduce the blinding effect it had if he kept it on its highest beam. And he followed it. The shifting shape of the wolf would move in and out of sight, always making its slow deliberate strides ahead of him - fifty paces away."
    },
    {
        "title": "Little Red Line",
        "url": "/posts/little-red-line/",
        "date": "2025-01-31",
        "dateDisplay": "January 31 2025",
        "excerpt": "You should own a domain. Pay a reasonable amount for it so it feels like it matters. Let the domain name be as close as possible to your own name. Allow me to explain why as I fight the urge to turn this into a grand-standing, self-righteous rant on the evils and non-necessity of social media. Suffice to say - just get off them, get off them all."
    },
    {
        "title": "Stapler",
        "url": "/posts/stapler/",
        "date": "2025-01-27",
        "dateDisplay": "January 27 2025",
        "excerpt": "His neck had got stuck in the barbed wire at the top of the wall. He could feel the blood running down the front of his shirt. It was starting to dry and harden in parts. If he tried to move from the ledge he was standing on to throw his right leg over - he would do damage that would guarantee the attention of a couple more of the crew at Bornley Heath Medical Centre. He didn’t know the exact effect the array of broken glass would have on his leg but he knew it would be bad. The bigger problem was knowing that he would definitely need a couple stabs at it. There was a nurse at Bornley Heath Medical Centre that reminded him of his Mum."
    },
    {
        "title": "The Cricket",
        "url": "/posts/the-cricket/",
        "date": "2025-01-26",
        "dateDisplay": "January 26 2025",
        "excerpt": "I have no hair on my inner thighs I rub my legs together like a cricket"
    },
    {
        "title": "Benedict Fellowship",
        "url": "/posts/benedict-fellowship/",
        "date": "2025-01-10",
        "dateDisplay": "January 10 2025",
        "excerpt": "We have our first member. Last night I took my seat for a drink with a friend. Two minutes later he walked in. We grabbed a beer and sat back down. He reached in his pocket and carefully retrieved a sealed plastic baggy. What precious loot was this? This first follower handed me an egg and took his place as a member of the Benedict Fellowship."
    },
    {
        "title": "The Bluebells",
        "url": "/posts/the-bluebells/",
        "date": "2024-12-28",
        "dateDisplay": "December 28 2024",
        "excerpt": "One day I will be a father. For as long as I can remember I have had an assurance that undertaking that role will be the greatest part of my life. I think about it so often. Its strange but I feel like I love my children already. My heart yearns for them desperately. I dread to think what I may write when they are eventually here with me - as my heart bursts open with such a great love."
    },
    {
        "title": "Help",
        "url": "/posts/help/",
        "date": "2024-12-16",
        "dateDisplay": "December 16 2024",
        "excerpt": "Being angry is remarkably easy. Knowing why you’re angry is the challenge."
    },
    {
        "title": "Make sense?",
        "url": "/posts/make-sense/",
        "date": "2024-10-22",
        "dateDisplay": "October 22 2024",
        "excerpt": "The mans name was Charles. He failed to - nor did he try to - create a vibrant environment for debate, where people were free to say whether they did or did not understand and ask questions. He definitely wanted the group to have done more reading outside the class. Our lack of preparation seemed to make the low engagement in our class our fault. If we wanted the class to be interesting, we ought to have worked on cultivating an interest to bring with us. Frankly, I get it."
    },
    {
        "title": "The Trickster",
        "url": "/posts/the-trickster/",
        "date": "2024-10-02",
        "dateDisplay": "October 02 2024",
        "excerpt": "I can be quite good in a crowd. I don’t mind coming across as emotional. I will pick a side and argue as passionately as I can for it, I may not even really believe what I am saying. I am just testing out how the words feel as I say them. Help me see differently and I will happily move toward your side. I will do so with very little embarrassment and without apology."
    },
    {
        "title": "I’m writing in a notebook",
        "url": "/posts/im-writing-in-a-notebook/",
        "date": "2024-08-20",
        "dateDisplay": "August 20 2024",
        "excerpt": "I haven’t given up on this. I’m writing in a notebook. I thought I would have more to say about things in the real world but I’m writing a bunch of nonsense made up stories. No plan it’s just strange stuff that’s popping up."
    },
    {
        "title": "Fragile breakthrough",
        "url": "/posts/fragile-breakthrough/",
        "date": "2024-07-09",
        "dateDisplay": "July 09 2024",
        "excerpt": "I think by the end of this blog post I am likely to find myself disagreeing with myself quite strongly. Lets go."
    },
    {
        "title": "I’m afraid I’ll lose everything",
        "url": "/posts/im-afraid-ill-lose-everything/",
        "date": "2024-07-07",
        "dateDisplay": "July 07 2024",
        "excerpt": "This definitely comes up a lot."
    },
    {
        "title": "Stomp",
        "url": "/posts/stomp/",
        "date": "2024-06-06",
        "dateDisplay": "June 06 2024",
        "excerpt": "Stop kicking down,  jump higher. Ankles twisted, shins bruised, worst case - concussed. Stop pretending. It only becomes a trick when you land it. Pretender! Worst won’t happen, if it never happens. Kick up, up and to the right. Jump up, stomp it. Bloody stomp it. Noone lands a kickflip, they stomp one. Never yet, maybe tonight. The last line will be written, not tonight."
    },
    {
        "title": "The Ducor comeback",
        "url": "/posts/the-ducor-comeback/",
        "date": "2024-06-04",
        "dateDisplay": "June 04 2024",
        "excerpt": "I had just turned a corner several storeys up and nearly walked straight into an empty elevator shaft plunging back down to earth. No bungy today. Instead, we stepped aside and round to a set of stairs that weaved equally precariously. It was dark in that stairwell. With each step the stairs themselves became increasingly variable - different heights, different widths, as though the architects instructions had been - “best guess”."
    },
    {
        "title": "Foreground first",
        "url": "/posts/foreground-first/",
        "date": "2024-05-29",
        "dateDisplay": "May 29 2024",
        "excerpt": "You look closer. You see mountains, reflected in a lake in the bottom third of the image. The remainder of the space shows the milky way, a sea of stars and vibrant colour. It’s a perfect photograph. Except, it isn’t. But no one would judge you for thinking so."
    },
    {
        "title": "Sorry for the wait",
        "url": "/posts/sorry-for-the-wait/",
        "date": "2024-05-28",
        "dateDisplay": "May 28 2024",
        "excerpt": "Spray the counter, wipe the wall. Empty the drawer, stack, restack. Sorry for the wait, we’re understaffed. No we’re not, we need new staff. Yes, I was pretending, I was ignoring you. I am overwhelmed, blocking everything out. Do I care about your sandwich? No, why would I? What are the rights here? This is about me, I am selling my time, to them. Not you.So yes, I was doing something, I was doing nothing. Sorry you saw, we’re understaffed. No we’re not, we need new staff."
    },
    {
        "title": "Mrs Greene’s invitation",
        "url": "/posts/mrs-greenes-invitation/",
        "date": "2024-05-05",
        "dateDisplay": "May 05 2024",
        "excerpt": "“It’s time to go.”"
    },
    {
        "title": "It self-destructs",
        "url": "/posts/it-self-destructs/",
        "date": "2024-05-03",
        "dateDisplay": "May 03 2024",
        "excerpt": "Self-destructing album, gig. Self-destructing small, big. Self-destructing letter, call. Self-destructing summer,fall. Self-destructing finished, task. Self-destructing answer, ask. Self-destructing more, less. Self-destructing checkers, chess."
    },
    {
        "title": "It started by starting",
        "url": "/posts/it-started-by-starting/",
        "date": "2024-05-03",
        "dateDisplay": "May 03 2024",
        "excerpt": "What to do if there is nothing?  What the hell do we do? Let’s just eat. Let’s just sit. There is nothing, right. There is nothing right. Let’s do nothing, let’s do. No one will remember. If nothing ever happened, nothing ever will. I think something just showed up, it started by starting. What do we do if there’s something? What on earth will we do? There’s something, right. There’s something right. Let’s do something, let’s do. Someone will remember. If something started happening, something surely will. Let’s do what we can, let’s eat, let’s sit. I think something showed up, it started by starting. It proved something right, it showed us that nothing,was never in sight."
    },
    {
        "title": "Bad Marketing Campaigns #1",
        "url": "/posts/bad-marketing-campaigns-1/",
        "date": "2024-05-02",
        "dateDisplay": "May 02 2024",
        "excerpt": "Feel like you’re too in the loop? Fed up of productive meetings where all necessary parties are informed? Ready to take the next step and blame people for not watching your training videos?"
    },
    {
        "title": "Jury Radio",
        "url": "/posts/jury-radio/",
        "date": "2024-05-01",
        "dateDisplay": "May 01 2024",
        "excerpt": "I cannot listen to the radio. Maybe it’s because Martin Kemp from Spandau Ballet and Eastenders shunned me at the ice rink when I was a kid. That’s another story. Anyway, the radio drives me mad."
    },
    {
        "title": "Something is velcro",
        "url": "/posts/something-is-velcro/",
        "date": "2024-04-28",
        "dateDisplay": "April 28 2024",
        "excerpt": "My legs were bound, I made a hop-ker-shuffle closer and closer to the edge. My toes were set over the side of one of the highest bridges in the world. I would fall for five seconds. One Mississippi, two Mississippi, three Mississippi, four Mississippi, five."
    },
    {
        "title": "Rednaz reflects",
        "url": "/posts/rednaz-reflects/",
        "date": "2024-04-27",
        "dateDisplay": "April 27 2024",
        "excerpt": "“Yes I know he and I are much the same.”"
    },
    {
        "title": "A poem about eczema",
        "url": "/posts/a-poem-about-eczema/",
        "date": "2024-04-27",
        "dateDisplay": "April 27 2024",
        "excerpt": "Are you serious? Who cares about your eczema? So what if it’s hot? So what if it’s itchy? No one cares. Quite right. What would even make this a poem? Ask me about it to my face. Maybe a five-year-old will reply. He usually does. Leave it alone, you’ll only make it worse."
    },
    {
        "title": "Snerol’s studio",
        "url": "/posts/snerols-studio/",
        "date": "2024-04-24",
        "dateDisplay": "April 24 2024",
        "excerpt": "“Was it justified this time?” Mrs Greene asked as she entered her classroom. Before Nodnarb had chance to answer she continued, “You’ll both need to move on, the year eights will arrive any moment.”"
    },
    {
        "title": "More paper please",
        "url": "/posts/more-paper-please/",
        "date": "2024-04-23",
        "dateDisplay": "April 23 2024",
        "excerpt": "You sit on a stool in the corner of the sports hall and try not to fall asleep. That’s the job of an A-Level exam invigilator."
    },
    {
        "title": "Nodnarb’s neck",
        "url": "/posts/nodnarbs-neck/",
        "date": "2024-04-22",
        "dateDisplay": "April 22 2024",
        "excerpt": "Snerol was afraid of everything. He was tall, but he had those eyes that always looked as though they were peering up at you. He was a people watcher, not out of curiosity so much, mostly he just wanted to know which of the people nearby should be avoided. He liked to make lists, always good to have his priorities straight. He could never quite tell whether he should be grateful or not that Nodnarb had decided to befriend him."
    },
    {
        "title": "The climats don’t change",
        "url": "/posts/the-climats-dont-change/",
        "date": "2024-04-21",
        "dateDisplay": "April 21 2024",
        "excerpt": "It is going to be one of two options. Where it is precisely is what will make all the difference. Oh, and everyone else is going to do the exact same thing."
    },
    {
        "title": "The liquids bags are dead",
        "url": "/posts/the-liquids-bags-are-dead/",
        "date": "2024-04-14",
        "dateDisplay": "April 14 2024",
        "excerpt": "The boards all flashed red. I knew they affected me but I couldn’t influence them. They indicated it would be another trip where clearing security would take a long while. I opened my backpack, took out my liquids bag, took my belt off, juggled my laptop as I repeatedly kicked my carry-on to keep up with the couple trudging on ahead of me."
    },
    {
        "title": "Poetic nonsense",
        "url": "/posts/poetic-nonsense/",
        "date": "2024-04-09",
        "dateDisplay": "April 09 2024",
        "excerpt": "‘Kathy’s Song’ by Simon & Garfunkel. But it has to be the Live in St Louis, MO – November 1969 version."
    },
    {
        "title": "The Great Mue",
        "url": "/posts/the-great-mue/",
        "date": "2024-04-08",
        "dateDisplay": "April 08 2024",
        "excerpt": "The car from Kambia to Makeni was long and not too comfortable, but the roads were good. Most of the roads in Sierra Leone are excellent."
    },
    {
        "title": "Further down",
        "url": "/posts/further-down/",
        "date": "2024-04-07",
        "dateDisplay": "April 07 2024",
        "excerpt": "Time on the surface. Short chopping breaths. Quick flying kicks. They love to distract. I long to detract. It is there at the bottom. It is always further down. If only I were earnest. I hope I mean, what I say."
    },
    {
        "title": "The Stowaway (for Percy)",
        "url": "/posts/the-stowaway-for-percy/",
        "date": "2024-04-07",
        "dateDisplay": "April 07 2024",
        "excerpt": "I just wanted an adventure. I should not have been there. Hiding below. Thank God he cared for me. Trapped with hope, until it sinks. So too I. Thank God he cared for me. I was not planned for. No supplies, no bed, no role reserved. Thank God he cared for me. We carried the Caird. My feet frozen through, the stowaway now useless. Thank God he cared for me. He sailed as we waited. Inhospitable refuge. I was in agony. Thank God he cared for me. There because I had hidden. He acted as if I were chosen. He fed me. He led me. He returned for me. Thank God he cared for me."
    },
    {
        "title": "Crude naif prig",
        "url": "/posts/crude-naif-prig/",
        "date": "2024-04-04",
        "dateDisplay": "April 04 2024",
        "excerpt": "I adore C.S Lewis’ essay ‘The Inner Ring’. Remarkably simply he outlines the life of an ‘Inner Ringer’, someone who spends their life seeking to make their way into inner rings – small groups – to gain benefits; “power, money, liberty to break rules, avoidance of routine duties, evasion of discipline” but above all a feeling and evidence of secret intimacy with the ‘others’."
    },
    {
        "title": "Who knows",
        "url": "/posts/who-knows/",
        "date": "2024-04-03",
        "dateDisplay": "April 03 2024",
        "excerpt": "It’s dark out, who is home? Let them come in, they are alone. It’s a cliff they are on, I don’t think they know. There really is nowhere else to go, let’s wait. We’ll see. Which of them will come to me."
    },
    {
        "title": "I am not calm",
        "url": "/posts/i-am-not-calm/",
        "date": "2024-04-02",
        "dateDisplay": "April 02 2024",
        "excerpt": "I am filling up, I cannot write. I am jamming the airways, cover my ears. Close my eyes. My mind is full and I am at the limit. I am not calm. I am not ready for quiet."
    },
    {
        "title": "Many uses for a Buff",
        "url": "/posts/many-uses-for-a-buff/",
        "date": "2024-04-02",
        "dateDisplay": "April 02 2024",
        "excerpt": "He is an excellent runner. He is an exceptional runner. He has run the Dragons Back and the Spine."
    },
    {
        "title": "EBI: Tamper, Sellers Wheel: 3/10",
        "url": "/posts/ebi-tamper-sellers-wheel-3-10/",
        "date": "2024-04-02",
        "dateDisplay": "April 02 2024",
        "excerpt": "It seems to be a common issue with a lot of eggs benedicts I am seeing recently. It’s unbalanced. A good eggs benedict – like most of life’s great pleasures – is an exercise in restraint, not excess."
    },
    {
        "title": "22:22",
        "url": "/posts/2222/",
        "date": "2024-03-29",
        "dateDisplay": "March 29 2024",
        "excerpt": "That’s the time as I write this post. Let’s make it short. I’m turning 30 in two hours."
    },
    {
        "title": "Surrounded by Idiots",
        "url": "/posts/surrounded-by-idiots/",
        "date": "2024-03-25",
        "dateDisplay": "March 25 2024",
        "excerpt": "‘Scar’ from The Lion King is probably not a model to be emulated."
    },
    {
        "title": "EBI - A brunch index you cant trust",
        "url": "/posts/ebi-a-brunch-index-you-cant-trust/",
        "date": "2024-03-21",
        "dateDisplay": "March 21 2024",
        "excerpt": "Here’s the vision. You’re in Barcelona. You wake up naturally at 9:17. You have a shower and put on your Birks, shorts and a short sleeve shirt with one more button undone than your comfy with and head out the door."
    },
    {
        "title": "What?",
        "url": "/posts/what/",
        "date": "2024-03-21",
        "dateDisplay": "March 21 2024",
        "excerpt": "Daniel Kaluuya told an excellent story in an interview with Rick Rubin. It was from his time acting opposite Josh Brolin in Sicario. I have not seen the film at the time of writing."
    },
    {
        "title": "We butchered a model",
        "url": "/posts/we-butchered-a-model/",
        "date": "2024-03-20",
        "dateDisplay": "March 20 2024",
        "excerpt": "The Thomas-Kilmann Conflict Mode Instrument (TKI) seems wrong. Well, maybe not wrong, but it fails to make the ideal immediately evident."
    },
    {
        "title": "Thank you Lemn",
        "url": "/posts/thank-you-lemn/",
        "date": "2024-03-19",
        "dateDisplay": "March 19 2024",
        "excerpt": "Lemn Sissay’s memoir of his childhood “My Name is Why” was excellent. There’s one page, I shan’t ruin it, but I will say I made special effort to read every word. A 5 word sentence repeated 91 times. It is the centre of the book. As I read the page it stood on, I hoped it would remain with me. I have thought about it again several times in the past two days. The sentiment it expresses is perfectly unique to the story he is telling, while remaining universal."
    },
    {
        "title": "Blog Rules",
        "url": "/posts/blog-rules/",
        "date": "2024-03-18",
        "dateDisplay": "March 18 2024",
        "excerpt": "I missed the golden age of blogs and I am not interested in social media. I am sure I would enjoy social media at its best but I think its presently happy with infamy. But man, we breezed through the era of the blogosphere. Straight through. Sad.I have an immense love for blogs as an idea. They seemed like one of the best things we could do with the internet and I think we may have squandered it. Admittedly, I don’t know much about them and maybe the blog-type sites today are ‘Medium’ or ‘Substack’, but I don’t know about those platforms, so here we are."
    }
];
